# Generated by Django 5.0.3 on 2024-03-13 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=20)),
                ("branch", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                (
                    "mobile_number",
                    models.CharField(
                        help_text="Enter your mobile number", max_length=15, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter your email address",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(help_text="Enter your password", max_length=128),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("branch_course", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(max_length=100)),
                (
                    "image_teacher",
                    models.ImageField(blank=True, null=True, upload_to="teachers/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collegeassessment.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_full_name", models.CharField(max_length=60)),
                ("subject_short_name", models.CharField(max_length=15)),
                ("subject_code", models.CharField(max_length=20)),
                (
                    "course_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collegeassessment.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="userdetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=40)),
                (
                    "confirm_password",
                    models.CharField(
                        help_text="Enter above passord Correctly", max_length=40
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(help_text="Enter Phone Number", max_length=10),
                ),
                (
                    "roll_number",
                    models.CharField(
                        help_text="Enter Permanent Roll Number", max_length=20
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collegeassessment.course",
                    ),
                ),
            ],
        ),
    ]
