# Generated by Django 5.0.3 on 2024-03-13 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "collegeassessment",
            "0002_remove_assignment_course_remove_subject_course_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_full_name", models.CharField(max_length=60)),
                ("subject_short_name", models.CharField(max_length=15)),
                ("subject_code", models.CharField(max_length=20)),
                (
                    "course_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="collegeassessment.course",
                    ),
                ),
            ],
        ),
    ]
