# Generated by Django 5.0.3 on 2024-03-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collegeassessment", "0003_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(max_length=40)),
                (
                    "mobile_number",
                    models.CharField(
                        help_text="Enter your mobile number", max_length=15, unique=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter your email address",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(help_text="Enter your password", max_length=128),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField()),
                ("address", models.CharField(max_length=100)),
                (
                    "image_teacher",
                    models.ImageField(blank=True, null=True, upload_to="teachers/"),
                ),
            ],
        ),
    ]
