# Generated by Django 5.0.3 on 2024-03-13 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collegeassessment", "0004_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="teacher_sub",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collegeassessment.course",
            ),
        ),
    ]
