# Generated by Django 5.0.3 on 2024-03-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collegeassessment", "0007_userdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_title", models.CharField(max_length=30)),
                ("assignment_description", models.TextField(max_length=200)),
                ("submission_last_date", models.DateField()),
                ("assignment_marks", models.CharField(max_length=10)),
                (
                    "assignment_file",
                    models.FileField(blank=True, null=True, upload_to="assignment/"),
                ),
            ],
        ),
    ]
