# Generated by Django 5.0.3 on 2024-03-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collegeassessment", "0008_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="collegeassessment.course",
            ),
        ),
    ]
