# Generated by Django 5.0.3 on 2024-03-13 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collegeassessment", "0011_news"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="News",
            new_name="New",
        ),
    ]
