# Generated by Django 5.0.3 on 2024-03-13 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collegeassessment", "0013_upload"),
    ]

    operations = [
        migrations.RenameField(
            model_name="upload",
            old_name="ass_desc",
            new_name="assignment_description",
        ),
        migrations.RenameField(
            model_name="upload",
            old_name="upload_ass",
            new_name="upload_assignment",
        ),
    ]
