# Generated by Django 5.0.3 on 2024-03-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "collegeassessment",
            "0014_rename_ass_desc_upload_assignment_description_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsByTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_description", models.CharField(max_length=200)),
                (
                    "news_by_teacher",
                    models.FileField(blank=True, null=True, upload_to="newsbyteacher/"),
                ),
            ],
        ),
    ]
