# Generated by Django 5.0.3 on 2024-03-13 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("collegeassessment", "0015_newsbyteacher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsByTeacher",
        ),
    ]
