# Generated by Django 5.0.3 on 2024-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collegeassessment", "0016_delete_newsbyteacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsByTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("news_title", models.CharField(max_length=30)),
                ("news_description", models.TextField(max_length=200)),
            ],
        ),
    ]
